---
title: "DATA609 HW8"
author: "Bin Lin"
date: "2017-10-18"
output: html_document
---

Page 347:
4. We have engaged in a business venture. Assume the probability of success is P(s) = 2/5; further assume that if we are successful we make $55,000, and if we are unsuccessful we lose $1750. Find the expected value of the business venture.


$E(s)=2/5*55000-(1-2/5)*1750=20950$


6. Consider a firm handling concessions for a sporting event. The firm's manager needs to know whether to stock up with coffee or cola and is formulating policies for specific weather predictions. A local agreement restricts the firm to selling only one type of beverage. The firm estimates a $1500 profit selling cola if the weather is cold and a $5000 profit selling cola if the weather is warm. The firm also estimates a $4000 profit selling coffee if it is cold and a $1000 profit selling coffee if the weather is warm. The weather forecast says that there is a 30% of a cold front; otherwise, the weather will be warm. Build a decision tree to assist with the decision. What should the firm handling concessions do?


```{r}
require("Rgraphviz")
cold <- 0.3
cola_cold <- 1500
cola_warm <- 5000
coffee_cold <- 4000
coffee_warm <- 1000

node1 <- "Profit"
node2 <- "Cola"
node3 <- "Coffee"
node4 <- "Cola Profit given Cold Weather"
node5 <- "Cola Profit given Warm Weather"
node6 <- "Coffee Profit given Cold Weather"
node7 <- "Coffee Profit given Warm Weather"

nodeNames <- c(node1, node2, node3, node4, node5, node6, node7)
rEG <- new("graphNEL", nodes=nodeNames, edgemode="directed")

rEG <- addEdge(nodeNames[1], nodeNames[2], rEG, 1)
rEG <- addEdge(nodeNames[1], nodeNames[3], rEG, 1)
rEG <- addEdge(nodeNames[2], nodeNames[4], rEG, 1)
rEG <- addEdge(nodeNames[2], nodeNames[5], rEG, 1)
rEG <- addEdge(nodeNames[3], nodeNames[6], rEG, 1)
rEG <- addEdge(nodeNames[3], nodeNames[7], rEG, 1)

eAttrs <- list()
q<-edgeNames(rEG)
eAttrs$label <- c("", "", "0.3 * 1500", "0.7 * 5000", "0.3 * 4000", "0.7 * 1000")
names(eAttrs$label) <- c(q[1],q[2], q[3], q[4], q[5], q[6])
edgeAttrs <- eAttrs

attributes<-list(node=list(label="foo", fillcolor="lightgreen", fontsize="24"), edge=list(color="red"),graph=list(rankdir="LR"))
 
plot(rEG, edgeAttrs=eAttrs, attrs=attributes)
#nodes(rEG)
#edges(rEG)
```


$E(Cola)=1500*0.3+5000*(1-0.3)=3950$

$E(Coffee)=4000*0.3+1000*(1-0.3)=1900$

Therefore , the firm should decide to sell cola.


Page 364
3. A big private oil company must decide whether to drill in the Gulf of Mexico. It costs $1 million to drill, and if oil is found its value is estimated at $6 million. At present, the oil company believes that there is a 45% chance that oil is present. Before drilling begins, the big private oil company can hire a geologist for $100,000 to obtain samples and test for oil. There is only about a 60% chance that the geologist will issue a favorable report. Given that the geologist does issue a favorable report, there is an 85% chance that there is oil. Given an unfavorable report, there is a 22% chance that there is oil. Determine what the big private oil company should do.

$E(With\quad Geneologist)=(6-1)*0.45-1*0.55=1.7$

$E(Without\quad Geneologist)=0.6*[(6-1)*0.85-1*0.15]\quad +\quad 0.4[(6-1)*0.22-0.78*1]-0.1=0.6*4.1+0.4*0.32-0.1=2.488$

Therefore, the big private oil company should hire the geologist. The estimated profit is 2.488million.